### ISSUE TITLE
possible fix

### ISSUE THREAD

**Issue by ghost** [srflp/vite-node16-moduleresolution-type-errors#1]
This is what I tried at least, I think it compiles just fine, you may need to inspect, the changes are:

* Do not use the line `vitest/globals` in tsconfig
* Use a config for vitest like the provided
* Install jest types ` npm i --save-dev @types/jest` (this is done with `npm i` now.

Here is the example: https://github.com/santimirandarp/vite-error-possible-fix/

**Comment by Maxim-Mazurok** [comment]
I think I was doing the same and it wasn't working... It seems like you're using deprecated `tsc` npm module, maybe that's why it works?
Also I see you're using sample.test.ts and I was using sample.spec.ts pretty sure it doesn't matter, but who knows...

**Comment by ghost** [comment]
I'm using 
```shell
tsc --version
Version 4.9.4
```

**Comment by Maxim-Mazurok** [comment]
That looks fine, still you don't need to install tsc as a seperate npm module, the tsc command comes with typescript npm module. Not that it matters tho, cheers!

**Comment by ghost** [comment]
Yes. I didn't realize it was in the `package.json` I probably copy&pasted from somewhere.
